# Generated by Django 5.2.15 on 2026-06-28 16:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('registered', 'Registered'), ('owner', 'Owner'), ('admin', 'Admin')], default='registered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'amenity',
            },
        ),
        migrations.CreateModel(
            name='BeachBar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('map_url', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.RESTRICT, related_name='beach_bars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beach_bar',
            },
        ),
        migrations.CreateModel(
            name='BeachBarAmenity',
            fields=[
                ('pk', models.CompositePrimaryKey('beach_bar', 'amenity', blank=True, editable=False, primary_key=True, serialize=False)),
                ('amenity', models.ForeignKey(db_column='amenity_id', on_delete=django.db.models.deletion.CASCADE, to='core.amenity')),
                ('beach_bar', models.ForeignKey(db_column='beach_bar_id', on_delete=django.db.models.deletion.CASCADE, to='core.beachbar')),
            ],
            options={
                'db_table': 'beach_bar_amenity',
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('beach_bar', models.ForeignKey(db_column='beach_bar_id', on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='core.beachbar')),
            ],
            options={
                'db_table': 'bundle',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='ReservationBundle',
            fields=[
                ('pk', models.CompositePrimaryKey('reservation', 'bundle', blank=True, editable=False, primary_key=True, serialize=False)),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bundle', models.ForeignKey(db_column='bundle_id', on_delete=django.db.models.deletion.RESTRICT, to='core.bundle')),
                ('reservation', models.ForeignKey(db_column='reservation_id', on_delete=django.db.models.deletion.CASCADE, to='core.reservation')),
            ],
            options={
                'db_table': 'reservation_bundle',
            },
        ),
        migrations.CreateModel(
            name='Sunbed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
                ('grid_row', models.PositiveSmallIntegerField()),
                ('grid_col', models.PositiveSmallIntegerField()),
                ('beach_bar', models.ForeignKey(db_column='beach_bar_id', on_delete=django.db.models.deletion.CASCADE, related_name='sunbeds', to='core.beachbar')),
            ],
            options={
                'db_table': 'sunbed',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='sunbed',
            field=models.ForeignKey(db_column='sunbed_id', on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='core.sunbed'),
        ),
        migrations.CreateModel(
            name='SunbedCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('beach_bar', models.ForeignKey(db_column='beach_bar_id', on_delete=django.db.models.deletion.CASCADE, related_name='sunbed_categories', to='core.beachbar')),
            ],
            options={
                'db_table': 'sunbed_category',
            },
        ),
        migrations.AddField(
            model_name='sunbed',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, related_name='sunbeds', to='core.sunbedcategory'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beach_bar', models.ForeignKey(db_column='beach_bar_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.beachbar')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='chk_review_rating')],
            },
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('sunbed', 'reservation_date'), name='uk_reservation_sunbed_date'),
        ),
        migrations.AddConstraint(
            model_name='sunbed',
            constraint=models.UniqueConstraint(fields=('beach_bar', 'label'), name='uk_sunbed_bar_label'),
        ),
    ]
